In [19]:
import pandas as pd
import numpy as np
import yfinance as yf
from statsmodels.tsa.holtwinters import Holt
import datetime
import warnings
import requests # Import the requests library
from scipy.stats import percentileofscore, spearmanr
from tabulate import tabulate
#warnings.simplefilter(action='ignore', category=FutureWarning)

In [20]:
### ======================
### Activos seleccionados
### ======================

#Acciones
Activos_historicos=['NVDA', 'BBVA', 'WMT',"CAT", "MU", "SNDK", "WELL", "WDC", "GEV", "GOOGL", "LITE", "AMD", "DELL"]

#ETFs
ETFs_historicos=["QQQM", 'VDC', 'GLD']

In [21]:
### =======================
### Parametros a considerar
### =======================

#Rentabilidad fija de la banca
R_f=0.0045

#Periodos de tiempo a considerar
periodos=[1,2,3,5,10]

In [25]:
### ===================
### Filtro de Acciones
### ===================


## Activo a evaluar

# nombre del activo
activo_input = input("Activo a evaluar: ").upper()

# Datos a 10 años
hoy = datetime.date.today()
start_10y=hoy-datetime.timedelta(days=10*365)

try:
    data=yf.download(activo_input, start=start_10y, end=hoy, progress=False, auto_adjust=True)['Close']
except:
    print("Error en la descarga de datos")

if data[activo_input].isnull().all():
    print("Activo '{activo_input}' no encontrado o sin datos")


## Analisis univariado

# calculo de metricas
    p=1
    dias=252
    df_p=data.tail(dias).dropna()

    # Retorno
    ret=((df_p-df_p.shift(1)).dropna()-1)

    # Rendimiento
    #rend=np.exp(ret.mean()*252)-1

    # Volatilidad


print(df_p)

Date
2016-09-12      5.940000
2016-09-13      5.740000
2016-09-14      6.040000
2016-09-15      6.020000
2016-09-16      6.050000
                 ...
2026-09-02    457.059998
2026-09-03    456.160004
2026-09-04    477.570007
2026-09-08    505.739990
2026-09-09    521.099976
Name: AMD, Length: 2512, dtype: float64

In [27]:
data.tail(100)

Ticker             AMD
Date
2026-04-17  278.390015
2026-04-20  274.950012
2026-04-21  284.489990
2026-04-22  303.459991
2026-04-23  305.329987
...                ...
2026-09-02  457.059998
2026-09-03  456.160004
2026-09-04  477.570007
2026-09-08  505.739990
2026-09-09  521.099976

[100 rows x 1 columns]

In [23]:
### Filtro de Acciones

## Fijar rentabilidad de la banca
R_f=0.045

## Periodos a evaluar
periodos=[1,2,3,5,10]

## Activo a evaluar
activo_input = input("Activo a evaluar: ").upper()


## Descarga de datos historicos
Data=Activos_historicos+[activo_input]

# período de tiempo de 5 años
hoy = datetime.date.today()
start_10y=hoy-datetime.timedelta(days=5*365)

data=yf.download(Data, start=start_10y, end=hoy, progress=False, auto_adjust=True)['Close']

data.head()

1 Failed download:
['']: ValueError('Empty ticker name')

Ticker,,AMD,BBVA,CAT,DELL,GEV,GOOGL,LITE,MU,NVDA,SNDK,WDC,WELL,WMT
Date,,,,,,,,,,,,,,
2021-09-13,NaN,104.800003,4.824885,189.208313,45.531078,NaN,140.990875,87.570000,72.501450,22.079540,NaN,44.009563,78.262207,45.421837
2021-09-14,NaN,105.730003,4.802921,185.657181,44.863472,NaN,141.200867,85.910004,71.662834,22.169243,NaN,43.279949,77.658974,45.183853
2021-09-15,NaN,105.599998,4.861494,188.777054,46.244724,NaN,143.068115,86.500000,71.984627,22.267920,NaN,43.821522,77.073456,45.262138
2021-09-16,NaN,106.220001,4.956674,186.822571,46.686733,NaN,142.256302,86.470001,72.774513,22.169243,NaN,43.836563,77.898476,45.412441
2021-09-17,NaN,103.879997,4.868815,183.289810,46.286163,NaN,139.472824,85.379997,72.452698,21.828363,NaN,43.565784,76.142006,45.318489